/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef split_CONSTANTS_H
#define split_CONSTANTS_H

#include "split_types.h"

namespace split {

class splitConstants {
 public:
  splitConstants();

  int16_t PORT;
};

extern const splitConstants g_split_constants;

} // namespace

#endif
