/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "split_constants.h"

namespace split {

const splitConstants g_split_constants;

splitConstants::splitConstants() {
  PORT = 9853;

}

} // namespace

